version: 2.1

jobs:
  lint:
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - run:
          name: Run Lint
          command: hadolint Dockerfile

  build-and-test:
    working_directory: ~/repo
    docker:
      - image: circleci/golang:1.15.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go mod download
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Run Test
          command: go test -v -short --count=1 $(go list ./...)
      - store_test_results:
          path: /tmp/test-reports

  build-and-push:
    docker:
      - image: cimg/base
    steps:
      - checkout
      - run:
          name: Build and Push Docker
          command: build_push_image_karsajobs.sh

workflows:
  lint-dockerfile:
    jobs:
      - lint
  test-app:
    jobs:
      - build-and-test
  build-app-karsajobs:
    jobs:
      - build-and-push
